version: '3'
services:
  ls-kafka-kafka:
    container_name: ls-kafka-kafka
    hostname: ls-kafka-kafka
    image: logstash:7.17.5
    restart: always
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      LS_JAVA_OPTS: '-Xms1024m -Xmx1024m'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
